config/routes.rb
NeverCoin::Application.routes.draw do
  devise_for :users, controllers: {
      registrations: "registrations",
      sessions: "sessions"
    },
    sign_out_via: [ :get, :delete, :post ]
  resources :payments
  get '/about' => 'statics#about'
  root to: "statics#launch"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can [:create, :update, :read], Payment, user_id: user.id
    can :manage, User, id: user.id
  end
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :user
  validates :bitcoin_address, presence: true, bitcoin_address: true
  validate :price, numericality: { less_than_or_equal_to: 0.07921921541289 }, presence: true
  validates :user, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :email, presence: true, email: true
  validates :stripe_customer_token, presence: true
  has_many :payments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def after_sign_in_path_for(user)
    payments_path
  end
end

app/controllers/payments_controller.rb
class PaymentsController < InheritedResources::Base
  actions :create, :index, :edit, :update, :new
  respond_to :html
  def new
    response = Typhoeus.get("https://coinbase.com/api/v1/currencies/exchange_rates")
    @rates = JSON.parse(response.body)
    gon.rates = @rates
    new!
  end
  def create
    response = Typhoeus.get("https://coinbase.com/api/v1/currencies/exchange_rates")
    rates = JSON.parse(response.body)
    exchange_rate = rates['usd_to_btc'].to_f

    @payment = Payment.new(new_permitted_params[:payment])
    @payment.exchange_rate = exchange_rate
    @payment.user = current_user
    authorize! :create, @payment

    customer = Stripe::Customer.retrieve(current_user.stripe_customer_token)
    card = if customer.cards and customer.cards.count > 0
      customer.cards.first
    else
      [
        {data: :cc_number, friendly: 'Credit Card Number'},
        {data: :cc_exp_month, friendly: 'Credit Card Expiration Month'},
        {data: :cc_exp_year, friendly: 'Credit Card Expiration Year'},
        {data: :cc_cvc, friendly: 'Credit Card Expiration CVC'},
        {data: :cc_name, friendly: 'Credit Card Expiration Name'}
      ].each do |feild|
        if params[feild[:data]].empty?
          @payment.errors[feild[:data]] << " is missing"
        end
      end
      if @payment.errors.empty?
        begin
          card = customer.cards.create(card: cc_from_skeuocard)
          current_user.last_4 = card.last4
          current_user.card_type = card.type
          current_user.save
        rescue Stripe::CardError => e
          @payment.errors[:credit_card] = e.message
        end
      end
    end

    if @payment.errors.empty?
      Retriable.retriable do
        begin
          amount = (@payment.price/exchange_rate)
          amount_with_fee = amount*1.06
          amount_with_fee_in_cents = (amount_with_fee.round(2)*100).to_i
          Stripe::Charge.create(
            amount: amount_with_fee_in_cents,
            currency: "usd",
            customer: customer,
            description: @payment.title
          )
        rescue StripeError => e
          @payment.errors[:credit_card] = e.message
        end
      end

      if @payment.errors.empty? and @payment.save

        coinbase_transaction_id = nil

        coinbase_transaction = Retriable.retriable do
          options = @payment.price < 0.01 ? {transaction: {user_fee: '0.0002'}} : {}
          $coinbase.send_money(@payment.bitcoin_address, @payment.price, "payment_id: #{@payment.id}", options)
        end

        @payment.coinbase_transaction_id = coinbase_transaction["transaction"]['id']

        if @payment.save
          flash[:notice] = "You successfully bought #{@payment.title}"
          redirect_to payments_path
        else
          gon.rates = rates
          @rates = rates
          render 'new'
        end
      else
        gon.rates = rates
        @rates = rates
        render 'new'
      end
    else
      gon.rates = rates
      @rates = rates
      render 'new'
    end
  end
  def index
    if current_user
      @payments = Payment.where(user_id: current_user.id)
      @payments.select!{|payment| can? :read, payment }
      index!
    else
      redirect_to root_path
    end
  end
  def update
    @payment = Payment.find(params[:id])
    @payment.update_attributes(update_permitted_params[:payment])
    if @payment.errors.empty?
      redirect_to payments_path
    else
      render 'edit'
    end
  end
protected
  def new_permitted_params
    params.permit(
      {payment: [:title, :description, :price, :bitcoin_address]},
      :cc_type, :cc_number, :cc_exp_month, :cc_exp_year, :cc_name, :cc_cvc
    )
  end
  def update_permitted_params
    params.permit(payment: [:title, :description])
  end

  def cc_from_skeuocard
    {
      number: new_permitted_params[:cc_number],
      exp_month: new_permitted_params[:cc_exp_month],
      exp_year: new_permitted_params[:cc_exp_year],
      cvc: new_permitted_params[:cc_cvc],
      name: new_permitted_params[:cc_name]
    }
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    params[:user][:password_confirmation] = params[:user][:password]
    User.transaction do
      @user = User.create(permitted_params[:user])
      stripe_customer = Stripe::Customer.create(email: permitted_params[:email])
      @user.stripe_customer_token = stripe_customer.id
      if @user.save
        sign_in :user, @user
        redirect_to new_payment_path
      else
        render 'new'
      end
    end
  end
protected
  def permitted_params
    params.permit(user: [:email, :password])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  def create
    params[:user][:remember_me] = '1'
    super
  end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def launch
  end
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title NeverCoin
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = include_gon
  %body
    = render 'shared/headers'
    .clearfix
    - if flash.keys.length > 0
      - flash.each do |name, msg|
        %div{class: "alert alert-success alert-dismissable", style: "top: 50px; position: relative;"}
          %button{type: "button", class: "close", 'aria-hidden' => "true", data: {dismiss: "alert"}}×
          = content_tag :div, msg, class: name
    .container{style: "top: 80px; position: relative; padding-bottom: 50px;"}
      .row
        = yield
    .footer{style: 'position: fixed; bottom: 0;display: block;width: 100%; padding: 10px;'}
      .container
        .footer-copyright.text-center{style: 'text-align: center;'} Copyright © 2014 Marc Beaupré

app/views/layouts/launch.html.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}/
    %title NeverCoin
    %meta{content: "initial-scale=1, maximum-scale=1, user-scalable=no", name: "viewport"}/
    %link{href: "css/site.min.css", rel: "stylesheet"}/
    %link{href: "http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,800,700,400italic,600italic,700italic,800italic,300italic", rel: "stylesheet", type: "text/css"}/
      <script src="js/html5shiv.js"></script>
      <script src="js/respond.min.js"></script>
    %script{src: "js/site.min.js", type: "text/javascript"}
  %body.home
    = yield

app/views/payments/_form.html.haml
= form_for(@payment) do |f|
  - if @payment.errors.any?
    #error_explanation
      %h6
        = pluralize(@payment.errors.count, "error")
        prohibited this payment from being saved:
      %ul
        - @payment.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.text_field :title, class: 'form-control', placeholder: 'Name of Product/Service'
    %br/
  .field
    = f.text_field :description, class: 'form-control', placeholder: 'Describe the item you bought'
    %br/
  .actions
    = f.submit "Update", class: "btn btn-primary btn-block"

app/views/payments/_new_form.html.haml
%h2 Make a Purchase
= form_for(@payment, html: {'data-parsley-validate' => true}) do |f|
  - if @payment.errors.any?
    #error_explanation
      %h6
        = pluralize(@payment.errors.count, "error")
        prohibited this payment from being saved:
      %ul
        - @payment.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.text_field :title, class: 'form-control', placeholder: 'Name of Product/Service'
  .field
    %br/
    %div{class: "input-group"}
      %span{class: "input-group-addon"} BTC
      = f.text_field :price, class: "form-control", placeholder: 'Price', required: true, 'data-parsley-min' => 0.5*@rates['usd_to_btc'].to_f, 'data-parsley-max' => 0.07921921541289
      %span#equivalent_usd_value{class: "input-group-addon"}= @payment.price ? "$#{((@payment.price.to_f/@rates['usd_to_btc'].to_f)*1.06).round(2)}" : ''
    %br/
  .field
    = f.text_field :bitcoin_address, required: true, class: 'form-control', placeholder: 'Bitcoin Address of merchant'
  - if not current_user.last_4
    %br/
    %div{style: "position: relative;left: 50%;"}
      = render 'skeuocard'
  %br/
  .actions
    %button{class: "btn btn-primary btn-block ladda-button", type: 'submit', data: {style: "slide-left"}}
      %span{class: "ladda-label"} Buy

:javascript
  $(window).ready(function(){
    var $skeuocard = $("#skeuocard");
    if($skeuocard.length > 0){
      new Skeuocard($("#skeuocard"));
    }
  });
  var usd_to_btc = gon.rates['usd_to_btc'];
  $('#payment_price').on('keyup', function (e) {
    var amount = parseFloat(e.target.value);
    if(amount){
      var cost = amount/usd_to_btc*1.06;
      $('#equivalent_usd_value').text('$'+cost.toFixed(2));
    }else{
      $('#equivalent_usd_value').text('');
    }
  });
  var ladda = Ladda.create( document.querySelector( '[type=submit]' ) )
  $.listen("parsley:field:error", function(){
    ladda.stop();
  })

app/views/payments/_skeuocard.html.haml
#skeuocard.credit-card-input.no-js{style: "left: -175px; position: relative;"}
  %p.no-support-warning
    Either you have Javascript disabled, or you're using an unsupported browser, amigo! That's why you're seeing this old-school credit card input form instead of a fancy new Skeuocard. On the other hand, at least you know it gracefully degrades...
  %label{for: "cc_type"} Card Type
  %select{name: "cc_type"}
    %option{value: ""} ...
    %option{value: "visa"} Visa
    %option{value: "mastercard"} MasterCard
    %option{value: "amex"} American Express
  %label{for: "cc_number"} Card Number
  %input#cc_number{maxlength: "19", name: "cc_number", placeholder: "XXXX XXXX XXXX XXXX", size: "19", type: "text"}/
  %label{for: "cc_exp_month"} Expiration Month
  %input#cc_exp_month{name: "cc_exp_month", placeholder: "00", type: "text"}/
  %label{for: "cc_exp_year"} Expiration Year
  %input#cc_exp_year{name: "cc_exp_year", placeholder: "00", type: "text"}/
  %label{for: "cc_name"} Cardholder's Name
  %input#cc_name{name: "cc_name", placeholder: "John Doe", type: "text"}/
  %label{for: "cc_cvc"} Card Validation Code
  %input#cc_cvc{maxlength: "3", name: "cc_cvc", placeholder: "123", size: "3", type: "text"}/

app/views/payments/edit.html.haml
%h1 Editing payment
= render 'form'
= link_to 'Back', payments_path

app/views/payments/index.html.haml
%div{class: "panel panel-primary"}
  %div{class: "panel-heading"}
    %h3{class: "panel-title"}
      Purchases
  %div{class: "panel-body"}
    %ul.list-group
      - @payments.each do |payment|
        %li.list-group-item{style: "margin-bottom: 0x; background-color: none; border: none;"}
          %a.price{data: {toggle: "tooltip", placement: "top"}, title: "BTC #{payment.price}"}
            $#{(payment.price/payment.exchange_rate).round(2)}
          %span.title{data: payment.description ? {toggle: "tooltip", placement: "top"} : {}, title: payment.description}
            = payment.title
          %span{class: 'badge badge-default'}>= link_to 'Edit', edit_payment_path(payment)
%br/
%a{href: new_payment_path, style: "color: white;"}
  %button{class: 'btn btn-orange btn-block'}
    Make a Purchase

:javascript
  $('[data-toggle="tooltip"]').tooltip();

app/views/payments/new.html.haml
= render 'new_form'

app/views/payments/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @payment.title
%p
  %strong Price:
  = @payment.price
%p
  %strong Bitcoin address:
  = @payment.bitcoin_address
%p
  %strong Description:
  = @payment.description
= link_to 'Edit', edit_payment_path(@payment)
|
=link_to 'Back', payments_path

app/views/shared/_headers.html.haml
%div{class: 'navbar navbar-default navbar-custom'}
  .container
    %div{class: 'navbar-header', style: "height: 20px; width: 100%"}
      %h4{style: 'float: left;'}
        = link_to 'NeverCoin', payments_path, style: "color: black;"
      = render "devise/shared/links", locals: {topbar: true}

app/views/statics/launch.html.haml
.docs-header.header--noBackground
  / index
  .index
    %h1
      NeverCoin
    %h2
      Spend Bitcoin with ease, without ever touching Bitcoin.
      %br
      Take advantage of steep discounts when you pay with Bitcoin.
    %p.start.Bootflat{style: "position: absolute; left: 50%;"}
      %a{href: new_user_registration_path, style: "color: white;"}
        %button{class: 'btn btn-primary btn-block', style: "width: 200px; height: 50px; position: absolute; right: -100px;"}
          Get Started
    .clearfix
    %p.learn_more
      %a
        Learn More